// THIS FILE IS AUTO-GENERATED BY scripts/generateReportMap.js
import dynamic from "next/dynamic";

// Dynamic imports
const Page1_1 = dynamic(() => import("@/app/report/section1/Page1"));
const Page1_2 = dynamic(() => import("@/app/report/section1/Page2"));

// Component mapping
export const componentMap: Record<string, React.ComponentType> = {
  "1-1": Page1_1,
  "1-2": Page1_2
};

// Legacy reportMap (for compatibility)
export const reportMap: Record<string,string> = {
  "1-1": "@/app/report/section1/Page1",
  "1-2": "@/app/report/section1/Page2"
};
